=== ConsumerDataStandardsAustralia/testdata-cli/src/schema/cdr-test-data-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "cdr-test-data-schema",
  "title": "Consumer Data Right Test Data JSON Schema",
  "description": "A JSON schema for defining test data files that can be used to seed a mock, or test, implementation of a Data Holder for the Consumer Data Right",
  "type": "object",
  "required": [
    "fileVersion",
    "standardsVersion",
    "title"
  ],
  "additionalProperties": false,
  "properties": {
    "fileVersion": {
      "type": "string",
      "description": "The version of the file formatted using semver (without extensions)",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
    },
    "standardsVersion": {
      "type": "string",
      "description": "The version of the CDR standards that these tests are validated for.  For formatted using semver (without extensions)",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
    },
    "title": {
      "type": "string",
      "description": "A short title of the test data file"
    },
    "description": {
      "type": "string",
      "description": "An optional description of the test data file to identify its purpose"
    },
    "holders": {
      "$ref": "#/defs/holders"
    },
    "clientCache": {
      "type": "array",
      "description": "A cache of previously registered clients",
      "items": {
        "$ref": "#/defs/client"
      }
    },
    "registerCache": {
      "type": "array",
      "description": "A cache of previously loaded recipients from the CDR Register",
      "items": {
        "$ref": "#/defs/recipient"
      }
    }
  },
  "defs": {
    "holders": {
      "type": "array",
      "description": "An array of holders and their data",
      "items": {
        "$ref": "#/defs/holderWrapper"
      }
    },
    "holderWrapper": {
      "type": "object",
      "description": "A wrapper for a single holder to contain all of the data related to the holder",
      "additionalProperties": false,
      "required": [
        "holderId",
        "holder"
      ],
      "properties": {
        "holderId": {
          "type": "string",
          "description": "The unique internal ID of the holder"
        },
        "holder": {
          "$ref": "#/defs/holder"
        }
      }
    },
    "holder": {
      "type": "object",
      "description": "Data for a single data holder",
      "additionalProperties": false,
      "required": [
        "unauthenticated",
        "authenticated"
      ],
      "properties": {
        "unauthenticated": {
          "$ref": "#/defs/unauthenticated"
        },
        "authenticated": {
          "$ref": "#/defs/authenticated"
        }
      }
    },
    "unauthenticated": {
      "type": "object",
      "description": "Unauthenticated data for a single data holder",
      "additionalProperties": false,
      "properties": {
        "banking": {
          "type": "object",
          "description": "Unauthenticated banking data",
          "additionalProperties": false,
          "properties": {
            "products": {
              "type": "array",
              "description": "An array of banking products",
              "items": {
                "$ref": "#/defs/bankProduct"
              }
            }
          }
        },
        "energy": {
          "type": "object",
          "description": "Unauthenticated energy data",
          "additionalProperties": false,
          "properties": {
            "plans": {
              "type": "array",
              "description": "An array of energy plans",
              "items": {
                "$ref": "#/defs/energyPlan"
              }
            }
          }
        },
        "admin": {
          "type": "object",
          "description": "Current system status",
          "additionalProperties": false,
          "properties": {
            "status": {
              "$ref": "#/defs/adminStatus"
            },
            "outages": {
              "type": "array",
              "description": "An array of planned outages",
              "items": {
                "$ref": "#/defs/adminOutage"
              }
            }
          }
        }
      }
    },
    "authenticated": {
      "type": "object",
      "description": "Authenticated data for a single data holder",
      "additionalProperties": false,
      "properties": {
        "customers": {
          "type": "array",
          "description": "An array of customers and their data",
          "items": {
            "$ref": "#/defs/customerWrapper"
          }
        }
      }
    },
    "client": {
      "type": "object",
      "description": "A previously registered client aligned to the current version of the data standards"
    },
    "recipient": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/register/RegisterDataRecipient.json"
    },
    "bankProduct": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingProductV6.json"
    },
    "energyPlan": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyPlan.json"
    },
    "adminStatus": {
      "type": "object",
      "description": "A status object for the holder"
    },
    "adminOutage": {
      "type": "object",
      "description": "A planned outage object for the holder"
    },
    "customerWrapper": {
      "type": "object",
      "description": "A wrapper for a single customer to contain all of the data related to the customer",
      "additionalProperties": false,
      "required": [
        "customerId",
        "customer"
      ],
      "properties": {
        "customerId": {
          "type": "string",
          "description": "The unique internal ID of the customer"
        },
        "customer": {
          "$ref": "#/defs/customer"
        },
        "banking": {
          "type": "object",
          "description": "Banking data for this customer",
          "properties": {
            "accounts": {
              "type": "array",
              "description": "An array of accounts and their data",
              "items": {
                "$ref": "#/defs/bankAccountWrapper"
              }
            },
            "directDebits": {
              "type": "array",
              "description": "An array of direct debit authorisations",
              "items": {
                "$ref": "#/defs/bankDirectDebit"
              }
            },
            "payees": {
              "type": "array",
              "description": "An array of payees",
              "items": {
                "$ref": "#/defs/bankPayee"
              }
            },
            "payments": {
              "type": "array",
              "description": "An array of payment schedules",
              "items": {
                "$ref": "#/defs/bankPaymentSchedule"
              }
            }
          }
        },
        "energy": {
          "type": "object",
          "description": "Energy data for this customer",
          "properties": {
            "accounts": {
              "type": "array",
              "description": "An array of accounts and their data",
              "items": {
                "$ref": "#/defs/energyAccountWrapper"
              }
            },
            "servicePoints": {
              "type": "array",
              "description": "An array of service points and their data",
              "items": {
                "$ref": "#/defs/energyServicePointWrapper"
              }
            }
          }
        }
      }
    },
    "customer": {
      "type": "object",
      "description": "A customer object aligned to the current version of the data standards",
      "properties": {
        "customerUType": {
          "enum": [
            "organisation",
            "person"
          ]
        },
        "person": {
          "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/common/CommonPersonDetailV2.json"
        },
        "organisation": {
          "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/common/CommonOrganisationDetailV2.json"
        }
      }
    },
    "bankDirectDebit": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingDirectDebit.json"
    },
    "bankPayee": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingPayeeDetailV2.json"
    },
    "bankPaymentSchedule": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingScheduledPaymentV2.json"
    },
    "bankAccountWrapper": {
      "type": "object",
      "description": "A wrapper for a single bank account to contain all of the data related to the account",
      "additionalProperties": false,
      "required": [
        "account"
      ],
      "properties": {
        "account": {
          "$ref": "#/defs/bankAccount"
        },
        "balance": {
          "$ref": "#/defs/bankAccountBalance"
        },
        "transactions": {
          "type": "array",
          "description": "An array of transactions for the account",
          "items": {
            "$ref": "#/defs/bankTransaction"
          }
        }
      }
    },
    "bankAccount": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingAccountDetailV5.json"
    },
    "bankAccountBalance": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingBalance.json"
    },
    "bankTransaction": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/banking/BankingTransactionDetailV3.json"
    },
    "energyAccountWrapper": {
      "type": "object",
      "description": "A wrapper for a single eenrgy account to contain all of the data related to the account",
      "additionalProperties": false,
      "required": [
        "account"
      ],
      "properties": {
        "account": {
          "$ref": "#/defs/energyAccount"
        },
        "balance": {
          "$ref": "#/defs/energyAccountBalance"
        },
        "paymentSchedule": {
          "type": "array",
          "description": "An array of agreed payment schedules",
          "items": {
            "$ref": "#/defs/energyPaymentSchedule"
          }
        },
        "invoices": {
          "type": "array",
          "description": "An array of invoices for the account",
          "items": {
            "$ref": "#/defs/energyInvoice"
          }
        },
        "transactions": {
          "type": "array",
          "description": "An array of transactions for the account",
          "items": {
            "$ref": "#/defs/energyTransaction"
          }
        },
        "concessions": {
          "type": "array",
          "description": "An array of concessions for the account",
          "items": {
            "$ref": "#/defs/energyConcession"
          }
        }
      }
    },
    "energyAccount": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyAccountDetailV4.json"
    },
    "energyAccountBalance": {
      "type": "object",
      "description": "Distributed energy resources for an energy account aligned to the current version of the data standards"
    },
    "energyPaymentSchedule": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyPaymentSchedule.json"
    },
    "energyInvoice": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyInvoice.json"
    },
    "energyTransaction": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyBillingTransactionV3.json"
    },
    "energyConcession": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyConcession.json"
    },
    "energyServicePointWrapper": {
      "type": "object",
      "description": "An energy for a single service point (metering site) to contain all of the data related to the service point",
      "additionalProperties": false,
      "required": [
        "account",
        "balance"
      ],
      "properties": {
        "servicePoint": {
          "$ref": "#/defs/energyServicePoint"
        },
        "der": {
          "$ref": "#/defs/energyDerData"
        },
        "usage": {
          "type": "array",
          "description": "An array of reads for the service point",
          "items": {
            "$ref": "#/defs/energyUsageRead"
          }
        }
      }
    },
    "energyServicePoint": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyServicePointDetailV2.json" 
    },
    "energyDerData": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyDerRecord.json"
    },
    "energyUsageRead": {
      "$ref": "https://raw.githubusercontent.com/ConsumerDataStandardsAustralia/dsb-schema-tools/main/1.35.0/schemas/energy/EnergyUsageRead.json"
    }
  }
}

=== ConsumerDataStandardsAustralia/testdata-cli/samples/files/just-customers.json
{
    "fileVersion": "1.1.0",
    "standardsVersion": "1.20.0",
    "title": "Create data holder",
    "description": "Test data generated by the CDR Test Data CLI",
    "holders": [
      {
        "holderId": "739181657",
        "holder": {
          "unauthenticated": {},
          "authenticated": {
            "customers": [
              {
                "customerId": "585059421",
                "customer": {
                  "customerUType": "organisation",
                  "organisation": {
                    "physicalAddresses": [
                      {
                        "purpose": "REGISTERED",
                        "addressUType": "paf",
                        "paf": {
                          "localityName": "Garden - Anderson",
                          "postcode": "3145",
                          "state": "Australian Capital Territory",
                          "postalDeliveryType": "LOCKED_BAG",
                          "postalDeliveryNumber": 26523047,
                          "dpid": "28095245",
                          "thoroughfareNumber1": 3456,
                          "thoroughfareNumber1Suffix": "HWY",
                          "thoroughfareNumber2": 3466,
                          "thoroughfareNumber2Suffix": "HWY",
                          "flatUnitType": "UNIT",
                          "floorLevelNumber": "48",
                          "streetName": "Jenkins Drive",
                          "streetType": "ROAD",
                          "lotNumber": "LOT 2",
                          "buildingName1": "Treasury Building"
                        }
                      },
                      {
                        "purpose": "PHYSICAL",
                        "addressUType": "simple",
                        "simple": {
                          "mailingName": "Marks - Reynolds",
                          "localityName": "Kreigershire",
                          "addressLine1": "Joseph Mews",
                          "postcode": "6761",
                          "city": "Tallahassee",
                          "state": "Australian Capital Territory",
                          "country": "AUS",
                          "addressLine3": "886"
                        }
                      },
                      {
                        "purpose": "OTHER",
                        "addressUType": "paf",
                        "paf": {
                          "localityName": "Jones - Collier",
                          "postcode": "2844",
                          "state": "Australian Capital Territory",
                          "postalDeliveryType": "LOCKED_BAG",
                          "postalDeliveryNumber": 27642234,
                          "flatUnitType": "UNIT",
                          "flatUnitNumber": "42",
                          "floorLevelNumber": "72",
                          "streetName": "Hudson Trail",
                          "streetType": "ROAD",
                          "streetSuffix": "E",
                          "lotNumber": "LOT 2",
                          "buildingName1": "Reception area"
                        }
                      }
                    ],
                    "agentRole": "Unspecified",
                    "businessName": "Goldner - Muller",
                    "organisationType": "OTHER",
                    "agentLastName": "Lynch",
                    "registeredCountry": "USA",
                    "isACNCRegistered": true
                  }
                }
              },
              {
                "customerId": "577606391",
                "customer": {
                  "customerUType": "person",
                  "person": {
                    "firstName": "Emily",
                    "lastName": "Graham",
                    "middleNames": [
                      "Reese"
                    ],
                    "phoneNumbers": [
                      {
                        "isPreferred": true,
                        "purpose": "INTERNATIONAL",
                        "countryCode": "+61",
                        "areaCode": "02",
                        "number": "02-4036-7003",
                        "extension": "x34",
                        "fullNumber": "+61 02-1144 7390"
                      },
                      {
                        "isPreferred": true,
                        "purpose": "HOME",
                        "countryCode": "+61",
                        "areaCode": "02",
                        "number": "02-5544-7993",
                        "extension": "x34",
                        "fullNumber": "+61 02-4907 7184"
                      },
                      {
                        "isPreferred": true,
                        "purpose": "MOBILE",
                        "countryCode": "+61",
                        "areaCode": "02",
                        "number": "02-8190-9103",
                        "extension": "x34",
                        "fullNumber": "+61 02-2022 1863"
                      }
                    ],
                    "emailAddresses": [
                      {
                        "isPreferred": true,
                        "purpose": "HOME",
                        "address": "Dylan_Hane@gmail.com"
                      },
                      {
                        "isPreferred": false,
                        "purpose": "HOME",
                        "address": "Jack_Moore94@gmail.com"
                      }
                    ],
                    "physicalAddresses": [
                      {
                        "purpose": "WORK",
                        "addressUType": "paf",
                        "paf": {
                          "localityName": "Rose Harber",
                          "postcode": "3719",
                          "state": "Australian Capital Territory",
                          "dpid": "27540006",
                          "floorLevelNumber": "77",
                          "streetName": "Matthew Square",
                          "streetType": "ROAD",
                          "streetSuffix": "E"
                        }
                      },
                      {
                        "purpose": "WORK",
                        "addressUType": "simple",
                        "simple": {
                          "mailingName": "Mr. Priscilla James",
                          "localityName": "South Aidenborough",
                          "addressLine1": "Dare Island",
                          "postcode": "6468",
                          "city": "Hempstead",
                          "state": "New South Wales",
                          "country": "AUS"
                        }
                      }
                    ],
                    "occupationCode": "113268",
                    "occupationCodeVersion": "ANZSCO_1220.0_2013_V1.3",
                    "lastUpdateTime": "2022-11-16T14:11:56.221Z",
                    "suffix": "Sr.",
                    "prefix": "Mr."
                  }
                }
              }
            ]
          }
        }
      }
    ]
  }
